//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressLine
    {
        public int AddressLineId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public int LineNumber { get; set; }
        public string AddressLine1 { get; set; }
        public Nullable<int> ObjectVersion { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
