//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASNSubPackage
    {
        public int ASNId { get; set; }
        public string MainPackageId { get; set; }
        public string SubPackageId { get; set; }
        public string PartNumber { get; set; }
        public string SubPackageType { get; set; }
        public string PackageTypeReferens { get; set; }
        public int SubPackageQuantity { get; set; }
        public Nullable<int> PackageStatusId { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string BatchNumber { get; set; }
        public string ChassisType { get; set; }
        public string ChassisNumber { get; set; }
        public int OriginalASNQuantity { get; set; }
        public string ParentPartNumber { get; set; }
        public string PartIdentityNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
        public string PartOrderNumber { get; set; }
    
        public virtual ASNMainPackage ASNMainPackage { get; set; }
    }
}
