//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoreplyOnPartAndDeliveryPoint
    {
        public string DepartmentId { get; set; }
        public string LocationId { get; set; }
        public string PartNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CrreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual DeliveryLocation DeliveryLocation { get; set; }
        public virtual Department Department { get; set; }
        public virtual Part Part { get; set; }
    }
}
