//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoScanner
    {
        public long AutoScannerId { get; set; }
        public string PackageNumber { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> PackageQuantity { get; set; }
        public string ASNId { get; set; }
        public string PalletType { get; set; }
        public int PalletFrames { get; set; }
        public Nullable<int> TransportAssignmentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
        public string PackageId { get; set; }
    }
}
