//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKDASNContainer
    {
        public int ASNId { get; set; }
        public string ContainerId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> OriginalCKDASNQuantity { get; set; }
        public Nullable<int> ReceivedQuantity { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CKDASNPart CKDASNPart { get; set; }
    }
}
