//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKDASNPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CKDASNPart()
        {
            this.CKDASNContainers = new HashSet<CKDASNContainer>();
        }
    
        public int ASNId { get; set; }
        public string PartNumber { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string FinalUnloadingPoint { get; set; }
        public bool DocumentDmissing { get; set; }
        public string ManualInvoiceNumber { get; set; }
        public Nullable<System.DateTime> ManualInvoiceDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CKDAdvanceShipmentNotice CKDAdvanceShipmentNotice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CKDASNContainer> CKDASNContainers { get; set; }
    }
}
