//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKDASNSubPackage
    {
        public int ASNId { get; set; }
        public string MainPackageId { get; set; }
        public int SubPackageId { get; set; }
        public string PartNumber { get; set; }
        public string Supplier { get; set; }
        public string BatchNumber { get; set; }
        public string RunningNo { get; set; }
        public Nullable<int> OrderTypeCode { get; set; }
        public Nullable<int> PackageStatusId { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> OriginalCKDASNQuantity { get; set; }
        public string PartAliasNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CKDASNMainPackage CKDASNMainPackage { get; set; }
    }
}
