//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentTransport
    {
        public int Id { get; set; }
        public int FromLine { get; set; }
        public string FromActivity { get; set; }
        public string PickupLocation { get; set; }
        public int ToLine { get; set; }
        public string ToActivity { get; set; }
        public string DeliveryLocation { get; set; }
        public bool Transport { get; set; }
        public string BufferDepartment { get; set; }
        public bool GroupAtToActivity { get; set; }
        public bool IndividualTransport { get; set; }
        public bool PrintLabel { get; set; }
        public string LabelType { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        public virtual ProductionLine ProductionLine1 { get; set; }
    }
}
