//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentOrderHandling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponentOrderHandling()
        {
            this.CustomerReceiverParts = new HashSet<CustomerReceiverPart>();
        }
    
        public string CustomerId { get; set; }
        public string ReceiverId { get; set; }
        public string Flow { get; set; }
        public string EndFactory { get; set; }
        public string ComponentFamily { get; set; }
        public string ComponentType { get; set; }
        public Nullable<int> ComponentGroupQuantity { get; set; }
        public Nullable<int> SequenceModeId { get; set; }
        public bool PreLoading { get; set; }
        public string TrailerTypeId { get; set; }
        public Nullable<int> InternalPalletTypeId { get; set; }
        public Nullable<int> CustomerPartNumberTypeId { get; set; }
        public bool RequirePacking { get; set; }
        public string PackingMasterGroupId { get; set; }
        public bool SequenceLoading { get; set; }
        public bool PartUniqueGrouping { get; set; }
        public bool DispatchTogether { get; set; }
        public bool MultiOrderOnSamePallet { get; set; }
        public string ExtPackReferenceNumber { get; set; }
        public bool SealNoRequired { get; set; }
        public string ExternalLabelType { get; set; }
        public bool ExportEntryDocRequired { get; set; }
        public bool EEDRequiredAfterDispatch { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
        public string ExternalPackingLabelType { get; set; }
        public bool KDBatch { get; set; }
        public bool ConsignmentNoteRequired { get; set; }
        public bool RequiredPartPreparation { get; set; }
    
        public virtual Label Label { get; set; }
        public virtual Label Label1 { get; set; }
        public virtual MasterGroup MasterGroup { get; set; }
        public virtual SequenceMode SequenceMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReceiverPart> CustomerReceiverParts { get; set; }
    }
}
