//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentCharacteristic
    {
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string ReceiverId { get; set; }
        public string Flow { get; set; }
        public string ComponentFamily { get; set; }
        public string Department { get; set; }
        public string LocationType { get; set; }
        public Nullable<int> ZoneNumber { get; set; }
        public string FixedLocation { get; set; }
        public string StorageType { get; set; }
        public int ObjectVersion { get; set; }
    }
}
