//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectedExecutionOrderType
    {
        public int Id { get; set; }
        public string ExecutionOrderType { get; set; }
        public int Line { get; set; }
        public string UsePoint { get; set; }
        public bool Obsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
