//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReceiverPart
    {
        public string Customer { get; set; }
        public string Receiver { get; set; }
        public string Flow { get; set; }
        public string EndFactory { get; set; }
        public string ComponentFamily { get; set; }
        public string ComponentType { get; set; }
        public string Part { get; set; }
        public Nullable<int> CustomsCodeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ObjectVersion { get; set; }
    
        public virtual ComponentOrderHandling ComponentOrderHandling { get; set; }
        public virtual Part Part1 { get; set; }
        public virtual SubPackageStatusCode SubPackageStatusCode { get; set; }
    }
}
