//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReceiver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerReceiver()
        {
            this.ComponentGroupExceptions = new HashSet<ComponentGroupException>();
            this.CustomerGroups = new HashSet<CustomerGroup>();
            this.CustomerReceiverAddresses = new HashSet<CustomerReceiverAddress>();
            this.CustomerReceiverFlows = new HashSet<CustomerReceiverFlow>();
            this.DispatchInvoiceInfoBasics = new HashSet<DispatchInvoiceInfoBasic>();
        }
    
        public string CustomerId { get; set; }
        public string ReceiverId { get; set; }
        public string CurrencyCode { get; set; }
        public bool DesAdv { get; set; }
        public string PaymentTerms { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
        public string Message3 { get; set; }
        public string Message4 { get; set; }
        public string Gate { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<int> TransportTimeDays { get; set; }
        public string MainFactoryId { get; set; }
        public string EndFactoryId { get; set; }
        public bool Customs { get; set; }
        public bool InternalCustomer { get; set; }
        public bool PrototypeCustomer { get; set; }
        public string SellerId { get; set; }
        public Nullable<int> ShipToAddressId { get; set; }
        public Nullable<int> InvoiceAddressId { get; set; }
        public Nullable<int> SellerAddressId { get; set; }
        public Nullable<int> MeansOfTransportId { get; set; }
        public Nullable<int> CustomerCodeId { get; set; }
        public bool GenerateComponentPackageId { get; set; }
        public bool InternalDispatchCheck { get; set; }
        public Nullable<int> SubPackageStatusCodeId { get; set; }
        public bool ShikyuReceiver { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentGroupException> ComponentGroupExceptions { get; set; }
        public virtual CustomerCode CustomerCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerGroup> CustomerGroups { get; set; }
        public virtual DispatchAddress DispatchAddress { get; set; }
        public virtual DispatchAddress DispatchAddress1 { get; set; }
        public virtual DispatchAddress DispatchAddress2 { get; set; }
        public virtual SubPackageStatusCode SubPackageStatusCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReceiverAddress> CustomerReceiverAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReceiverFlow> CustomerReceiverFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchInvoiceInfoBasic> DispatchInvoiceInfoBasics { get; set; }
    }
}
