//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrderHead()
        {
            this.CustomerOrderSequences = new HashSet<CustomerOrderSequence>();
            this.MainPackagePickings = new HashSet<MainPackagePicking>();
        }
    
        public long Id { get; set; }
        public string CustomerId { get; set; }
        public string ReceiverId { get; set; }
        public string AssemblyOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PackType { get; set; }
        public Nullable<int> PartOrderStatus { get; set; }
        public Nullable<int> PickStatus { get; set; }
        public Nullable<int> PackStatus { get; set; }
        public string LanguageDoc { get; set; }
        public string LanguageManual { get; set; }
        public string OrderPriority { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string KDBatchNo { get; set; }
        public Nullable<int> ASNId { get; set; }
        public int ObjectVersion { get; set; }
        public string KDOrderType { get; set; }
    
        public virtual AdvanceShipmentNotice AdvanceShipmentNotice { get; set; }
        public virtual AlternativeShipToAddress AlternativeShipToAddress { get; set; }
        public virtual CustomerOrderStatu CustomerOrderStatu { get; set; }
        public virtual ProcessStatu ProcessStatu { get; set; }
        public virtual ProcessStatu ProcessStatu1 { get; set; }
        public virtual ProcessStatu ProcessStatu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderSequence> CustomerOrderSequences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackagePicking> MainPackagePickings { get; set; }
    }
}
