//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderSequence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrderSequence()
        {
            this.CustomerOrderGoodsMarks = new HashSet<CustomerOrderGoodsMark>();
            this.LoadListSubItems = new HashSet<LoadListSubItem>();
            this.PartOrders = new HashSet<PartOrder>();
            this.PentaOrderPartNumbers = new HashSet<PentaOrderPartNumber>();
        }
    
        public string CPOId { get; set; }
        public long OrderHeadId { get; set; }
        public string Flow { get; set; }
        public System.DateTime GateDate { get; set; }
        public string EndFactory { get; set; }
        public string MainFactory { get; set; }
        public Nullable<int> ShipmentDeliveryNumber { get; set; }
        public int Quantity { get; set; }
        public string OrderStatus { get; set; }
        public string PurchaseId { get; set; }
        public string Gate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.DateTime> AdjustedShippingDate { get; set; }
        public bool Express { get; set; }
        public string LinesetNumber { get; set; }
        public int CustomerOrderTypeId { get; set; }
        public System.DateTime GateTime { get; set; }
        public string SalesOrdernumber { get; set; }
        public string Supplier { get; set; }
        public string ChassisType { get; set; }
        public string ChassisNumber { get; set; }
        public string PartNumber { get; set; }
        public string CustomerPartNumber { get; set; }
        public string VSMCNumber { get; set; }
        public string PentaPartNumber { get; set; }
        public string PentaPartNumberDesc { get; set; }
        public string CustomerOrderReference { get; set; }
        public string VolvoPallet { get; set; }
        public int DispatchedQuantity { get; set; }
        public string InvoiceOrderNumber { get; set; }
        public string CustomerReference { get; set; }
        public string GoodsSuffix { get; set; }
        public int GroupExceptionId { get; set; }
        public string ExternalOrderId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string FinalDeliveryGate { get; set; }
        public int ObjectVersion { get; set; }
        public string ProductionOrderClass { get; set; }
    
        public virtual ComponentOrder ComponentOrder { get; set; }
        public virtual CustomerOrderFlag CustomerOrderFlag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderGoodsMark> CustomerOrderGoodsMarks { get; set; }
        public virtual CustomerOrderHead CustomerOrderHead { get; set; }
        public virtual CustomerOrderType CustomerOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadListSubItem> LoadListSubItems { get; set; }
        public virtual LoosePartOrder LoosePartOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrder> PartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PentaOrderPartNumber> PentaOrderPartNumbers { get; set; }
    }
}
