//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReception
    {
        public string CustomerId { get; set; }
        public string ReceptionId { get; set; }
        public string AdressLine { get; set; }
        public string AdressLine2 { get; set; }
        public string AdressLine3 { get; set; }
        public string AdressLine4 { get; set; }
        public string AdressLine21 { get; set; }
        public string AdressLine22 { get; set; }
        public string AdressLine23 { get; set; }
        public string AdressLine24 { get; set; }
        public string CurrencyCode { get; set; }
        public string UsageOfEdi { get; set; }
        public int PARMANR { get; set; }
        public string ValueAddTaxIdentification { get; set; }
        public string Eu { get; set; }
        public int TermsOfPayment { get; set; }
        public int InvoiceDelayDays { get; set; }
        public string MessageLine { get; set; }
        public string MessageLine2 { get; set; }
        public string MessageLine3 { get; set; }
        public string MessageLine4 { get; set; }
        public string SPRAKKOD { get; set; }
        public string SUFFIX { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ExternalCustomerReceiver ExternalCustomerReceiver { get; set; }
    }
}
