//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public string PartOrderNumber { get; set; }
        public int PreliminaryCarrierId { get; set; }
        public string AdvanceShipmentNotice { get; set; }
        public System.DateTime GateTime { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public string OrderId { get; set; }
        public string Gate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual PartOrder PartOrder { get; set; }
        public virtual PreliminaryDeliveryNote PreliminaryDeliveryNote { get; set; }
        public virtual PreliminaryLoading PreliminaryLoading { get; set; }
    }
}
