//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnitPartWorkcell
    {
        public int Id { get; set; }
        public string DeliveryUnitId { get; set; }
        public string PartNumber { get; set; }
        public string Station { get; set; }
        public string ParentPartNumber { get; set; }
        public string FunctionGroup { get; set; }
        public string SubGroup { get; set; }
        public string Workcell { get; set; }
        public string ExecutionOrderId { get; set; }
        public decimal Quantity { get; set; }
        public int ObjectVersion { get; set; }
        public Nullable<int> Line { get; set; }
    
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
