//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryLocation()
        {
            this.AutoreplyOnPartAndDeliveryPoints = new HashSet<AutoreplyOnPartAndDeliveryPoint>();
            this.DeliveryLocationRejectCodes = new HashSet<DeliveryLocationRejectCode>();
            this.ExceptionsMaterialHandlingCodes = new HashSet<ExceptionsMaterialHandlingCode>();
            this.PartExceptions = new HashSet<PartException>();
        }
    
        public string LocationId { get; set; }
        public Nullable<int> PartOrderCategoryId { get; set; }
        public string DeliveryLocationId { get; set; }
        public string EmballageNote { get; set; }
        public string MainStorage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoreplyOnPartAndDeliveryPoint> AutoreplyOnPartAndDeliveryPoints { get; set; }
        public virtual Location Location { get; set; }
        public virtual PartOrderCategory PartOrderCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryLocationRejectCode> DeliveryLocationRejectCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionsMaterialHandlingCode> ExceptionsMaterialHandlingCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartException> PartExceptions { get; set; }
    }
}
