//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnitHasPassedStation
    {
        public int Id { get; set; }
        public string DeliveryUnit { get; set; }
        public string SerialNumber { get; set; }
        public int Department { get; set; }
        public string AssemblyLine { get; set; }
        public string Station { get; set; }
        public string ComponentType { get; set; }
        public string ComponentFamily { get; set; }
        public string TriggerType { get; set; }
        public System.DateTime PassedTime { get; set; }
        public string PhysicalStation { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual DeliveryUnit DeliveryUnit1 { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
