//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryUnit()
        {
            this.DeliveryUnitHasPassedStations = new HashSet<DeliveryUnitHasPassedStation>();
            this.DeliveryUnitParts = new HashSet<DeliveryUnitPart>();
        }
    
        public string DeliveryUnitId { get; set; }
        public string CPOId { get; set; }
        public System.DateTime StartTime { get; set; }
        public string SerialNumber { get; set; }
        public string ChassisId { get; set; }
        public string ChassisType { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Status { get; set; }
        public string PartNumberCH { get; set; }
        public string CustomerId { get; set; }
        public string CustomerReceiver { get; set; }
        public string CustomerFlow { get; set; }
        public string CVId { get; set; }
        public string EndFactoryCode { get; set; }
        public string SoftwareId { get; set; }
        public string OrderTypeId { get; set; }
        public string ProductUnitFamily { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string MasterItemId { get; set; }
        public string ProductionOrderType { get; set; }
        public string ProducingSiteName { get; set; }
        public string ProducingSiteId { get; set; }
        public string NextProductionOrderId { get; set; }
        public string NextUsePointId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool ExternalProduced { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string FinancialReference { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string OrderSystem { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LatestLoadTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual DeliveryUnitMasterItem DeliveryUnitMasterItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryUnitHasPassedStation> DeliveryUnitHasPassedStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryUnitPart> DeliveryUnitParts { get; set; }
        public virtual HardConnectedCBU HardConnectedCBU { get; set; }
    }
}
