//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnitStatusFilter
    {
        public int Id { get; set; }
        public string DisplayText { get; set; }
        public string InvolvedStatus { get; set; }
        public Nullable<bool> Included { get; set; }
        public Nullable<bool> ShowOnFilter { get; set; }
        public string Comment { get; set; }
        public int ObjectVersion { get; set; }
    }
}
