//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryUnitMainOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryUnitMainOrder()
        {
            this.DeliveryUnitMasterItems = new HashSet<DeliveryUnitMasterItem>();
        }
    
        public string MainOrderId { get; set; }
        public string OrderState { get; set; }
        public string BatchNumber { get; set; }
        public string VIN { get; set; }
        public string ProductClass { get; set; }
        public Nullable<System.DateTime> ChassisStartTime { get; set; }
        public string ChassisId { get; set; }
        public string ChassisType { get; set; }
        public Nullable<System.DateTime> SpecificationDate { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryUnitMasterItem> DeliveryUnitMasterItems { get; set; }
    }
}
