//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchInvoiceInfo
    {
        public int Id { get; set; }
        public string CPOId { get; set; }
        public string Supplier { get; set; }
        public string ProductionOrderId { get; set; }
        public string CustomerVATNo { get; set; }
        public Nullable<decimal> CustomerVATRate { get; set; }
        public string VATExemptRef { get; set; }
        public string IncoTermCode { get; set; }
        public string IncoTermText { get; set; }
        public string PaymentTerm { get; set; }
        public string ContractNoDate { get; set; }
        public string PassportOfDeal { get; set; }
        public string Currency { get; set; }
        public System.DateTime PlannedDueDate { get; set; }
        public System.DateTime PlannedDeliveryDate { get; set; }
        public Nullable<decimal> FreightCostBeforeBorder { get; set; }
        public Nullable<decimal> FreightCostAfterBorder { get; set; }
        public Nullable<decimal> FreightCost { get; set; }
        public string SellerOrganisationNo { get; set; }
        public string SellerVATNo { get; set; }
        public string HSClassification { get; set; }
        public decimal UnitPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> PartVATRate { get; set; }
        public Nullable<decimal> PartFreightCost { get; set; }
        public string CountryOfOrigin { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string SwiftCode { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string IBAN { get; set; }
        public string BillToName { get; set; }
        public string BillToStreet { get; set; }
        public string BillToPostalAddress { get; set; }
        public string BillToZipCode { get; set; }
        public string BillToCity { get; set; }
        public string BillToCountry { get; set; }
        public string BillToParmaId { get; set; }
        public string BillFromParmaId { get; set; }
        public string ShipFromParmaId { get; set; }
        public string UnitOfMeasure { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    }
}
