//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchInvoiceInfoBasic
    {
        public string CustomerId { get; set; }
        public string ReceiverId { get; set; }
        public string PartNumber { get; set; }
        public string Supplier { get; set; }
        public System.DateTime ValidDateFrom { get; set; }
        public Nullable<decimal> CustomerVATRate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> FreightCostBeforeBorder { get; set; }
        public Nullable<decimal> FreightCostAfterBorder { get; set; }
        public Nullable<decimal> FreightCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CustomerReceiver CustomerReceiver { get; set; }
        public virtual Part Part { get; set; }
    }
}
