//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmballageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmballageType()
        {
            this.PartProcesses = new HashSet<PartProcess>();
            this.LastOperationMachinings = new HashSet<LastOperationMachining>();
        }
    
        public string EmballageTypeId { get; set; }
        public string Description { get; set; }
        public string LocationSuffix { get; set; }
        public int LoadLength { get; set; }
        public int LoadWidth { get; set; }
        public int LoadHeight { get; set; }
        public string EmballageNumber { get; set; }
        public bool LoadImpact { get; set; }
        public bool StandardEmballage { get; set; }
        public decimal LoadWeight { get; set; }
        public bool PackageHolder { get; set; }
        public int QtyLabelsToPrint { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcess> PartProcesses { get; set; }
        public virtual EmballageTypeOccupyNoOfStow EmballageTypeOccupyNoOfStow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LastOperationMachining> LastOperationMachinings { get; set; }
    }
}
