//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTypeGroup
    {
        public int EventGroupId { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<int> ObjectVersion { get; set; }
    
        public virtual EventGroup EventGroup { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
