//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportASNPackage
    {
        public string AdvanceShipmentNotice { get; set; }
        public string PackageNumber { get; set; }
        public string PackageId { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public string PackageType { get; set; }
        public string OrderId { get; set; }
        public string Gate { get; set; }
        public int DeliveredQuantity { get; set; }
        public int PriceOfFreightInReceiversCurrency { get; set; }
        public int PriceOfFreight { get; set; }
        public int ProductsPriceInReceiversCurrency { get; set; }
        public int ProductsPriceInBaseCurrency { get; set; }
        public int NetWeight { get; set; }
        public System.DateTime CustomerNeedDate { get; set; }
        public string Individual { get; set; }
        public System.DateTime GateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ExportASNPackageNumber ExportASNPackageNumber { get; set; }
    }
}
