//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportASN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExportASN()
        {
            this.ExportASNPackageNumbers = new HashSet<ExportASNPackageNumber>();
        }
    
        public string AdvanceShipmentNotice { get; set; }
        public string Customer { get; set; }
        public int ReceptionId { get; set; }
        public string AdressLine { get; set; }
        public string AdressLine2 { get; set; }
        public string AdressLine3 { get; set; }
        public string AdressLine4 { get; set; }
        public System.DateTime AdvanceShipmentNoticeTime { get; set; }
        public string PartnerId { get; set; }
        public int ConsignmentNote { get; set; }
        public string CarrierId { get; set; }
        public string CarrierId2 { get; set; }
        public string MessageLine { get; set; }
        public string MessageLine2 { get; set; }
        public string MessageLine3 { get; set; }
        public string MessageLine4 { get; set; }
        public string CurrencyCode { get; set; }
        public string ConsignmentNote2 { get; set; }
        public int InvoiceDate { get; set; }
        public int DueTime { get; set; }
        public string AdressLine21 { get; set; }
        public string AdressLine22 { get; set; }
        public string AdressLine23 { get; set; }
        public string AdressLine24 { get; set; }
        public string Eu { get; set; }
        public string SupplierId { get; set; }
        public string ValueAddTaxIdentification { get; set; }
        public string BankAccount { get; set; }
        public string IbanNumber { get; set; }
        public decimal GrossWeight { get; set; }
        public int PackageSize { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public System.DateTime CustomerNeedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportASNPackageNumber> ExportASNPackageNumbers { get; set; }
    }
}
