//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalCustomerReceiver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalCustomerReceiver()
        {
            this.ExternalCustomerReceiverParts = new HashSet<ExternalCustomerReceiverPart>();
        }
    
        public string CustomerId { get; set; }
        public string ReceptionId { get; set; }
        public string LabelType { get; set; }
        public int CarrierType { get; set; }
        public string LoadGroup { get; set; }
        public string RANGERINGSGRUPP { get; set; }
        public int TIDLEVDAG { get; set; }
        public string TOMLASTGRUPP { get; set; }
        public string LoadingGroup { get; set; }
        public string PartnerId { get; set; }
        public string ContractId { get; set; }
        public string PaymentDirective { get; set; }
        public string IndividualAdvanceShipmentNotice { get; set; }
        public string AdressLine { get; set; }
        public string PartnerIdDescription { get; set; }
        public string Gate { get; set; }
        public string Color { get; set; }
        public int NumberOfDispatchNotes { get; set; }
        public int NumberOfDispatchNotes2 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CustomerReception CustomerReception { get; set; }
        public virtual ExternalCustomer ExternalCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCustomerReceiverPart> ExternalCustomerReceiverParts { get; set; }
    }
}
