//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalCustomerReceiverPart
    {
        public string CustomerId { get; set; }
        public string ReceptionId { get; set; }
        public string PartNumber { get; set; }
        public string TOMLASTGRUPP { get; set; }
        public int CarrierType { get; set; }
        public string LoadGroup { get; set; }
        public string RANGERINGSGRUPP { get; set; }
        public int TIDLEVDAG { get; set; }
        public int DeliveryQuantityOfInterval { get; set; }
        public int DeliveryTimeOfInterval { get; set; }
        public int PackageWeight { get; set; }
        public int PackageQuantity { get; set; }
        public int MinimumStorage { get; set; }
        public string RepackingGroup { get; set; }
        public string PickingGroupCode { get; set; }
        public bool LoadingCoOrdination { get; set; }
        public int LoadLength { get; set; }
        public int LoadWidth { get; set; }
        public int LoadHeight { get; set; }
        public string LoadingGroup { get; set; }
        public string SOKADRESS { get; set; }
        public int NumberOfPackages { get; set; }
        public string PackageReferenceCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ExternalCustomerReceiver ExternalCustomerReceiver { get; set; }
        public virtual ReceptionPartNumber ReceptionPartNumber { get; set; }
    }
}
