//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalCustomer()
        {
            this.ExternalCustomerReceivers = new HashSet<ExternalCustomerReceiver>();
        }
    
        public string CustomerId { get; set; }
        public int StatusOfPackage { get; set; }
        public string TOMLASTGRUPP { get; set; }
        public int CarrierType { get; set; }
        public string LoadGroup { get; set; }
        public string RANGERINGSGRUPP { get; set; }
        public int TIdLEVDAG { get; set; }
        public int AlarmWaitingPeriod { get; set; }
        public string LoadingGroup { get; set; }
        public string PartnerId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCustomerReceiver> ExternalCustomerReceivers { get; set; }
    }
}
