//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstOperationMachining
    {
        public string LocationId { get; set; }
        public string PartNumber { get; set; }
        public string DeliveryLocation { get; set; }
        public string StationDescription { get; set; }
        public string SubPartNumber { get; set; }
        public string ParentPartNumber { get; set; }
        public bool MachiningPlan { get; set; }
        public string UserId { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public bool IndividualReply { get; set; }
        public int QuantityOfMaterialToHandle { get; set; }
        public Nullable<int> QuantityOfMaterialToHandleInTransport { get; set; }
        public string StationId { get; set; }
        public bool BarCode { get; set; }
        public int MinimumStorage { get; set; }
        public bool FinishStarted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Part Part { get; set; }
    }
}
