//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericSystemParameter
    {
        public string SystemParameter { get; set; }
        public string ParameterDescription { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int ValueNumber { get; set; }
        public string ValueMark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifideTime { get; set; }
        public int ObjectVersion { get; set; }
    }
}
