//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryField
    {
        public int EventId { get; set; }
        public int EventFieldId { get; set; }
        public string Value { get; set; }
        public string OriginalValue { get; set; }
    
        public virtual EventField EventField { get; set; }
        public virtual HistoryEvent HistoryEvent { get; set; }
    }
}
