//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryWithdrawalType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryWithdrawalType()
        {
            this.InventoryWithdrawalOnLocations = new HashSet<InventoryWithdrawalOnLocation>();
            this.InventoryWithdrawalTypeDescriptions = new HashSet<InventoryWithdrawalTypeDescription>();
        }
    
        public int InventoryWithdrawalTypeId { get; set; }
        public string Description { get; set; }
        public int EventType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryWithdrawalOnLocation> InventoryWithdrawalOnLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryWithdrawalTypeDescription> InventoryWithdrawalTypeDescriptions { get; set; }
    }
}
