//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDBatchSizeOrder
    {
        public System.Guid Id { get; set; }
        public string KDBatchNo { get; set; }
        public string OrderNumber { get; set; }
        public string AssemblyStartDate { get; set; }
        public string AssemblyEndDate { get; set; }
    
        public virtual KDBatchSize KDBatchSize { get; set; }
    }
}
