//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KDBatchSize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KDBatchSize()
        {
            this.KDBatchSizeOrders = new HashSet<KDBatchSizeOrder>();
        }
    
        public string KDBatchNo { get; set; }
        public string ReleaseId { get; set; }
        public int Size { get; set; }
        public string PackingFactoryCode { get; set; }
        public string AssemblyFactoryCode { get; set; }
        public string PackingStartDate { get; set; }
        public string PackingEndDate { get; set; }
        public byte[] Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KDBatchSizeOrder> KDBatchSizeOrders { get; set; }
    }
}
