//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kit()
        {
            this.KitPreAssemblyPickupLocations = new HashSet<KitPreAssemblyPickupLocation>();
            this.KitTransportUnits = new HashSet<KitTransportUnit>();
            this.MasterGroupEquipments = new HashSet<MasterGroupEquipment>();
            this.StationDeliveryLocationKits = new HashSet<StationDeliveryLocationKit>();
            this.StationPartKits = new HashSet<StationPartKit>();
        }
    
        public string KitId { get; set; }
        public int KitTypeId { get; set; }
        public Nullable<int> StationChangeNoteId { get; set; }
        public Nullable<int> PartOrderTypeId { get; set; }
        public Nullable<int> TriggerTypeId { get; set; }
        public Nullable<int> NoOfPicks { get; set; }
        public bool PrintByExternalSystem { get; set; }
        public bool Active { get; set; }
        public string PickingGroup { get; set; }
        public bool VerifyPosition { get; set; }
        public Nullable<int> PreNumberOfBookings { get; set; }
        public Nullable<int> AdjustNeedTime { get; set; }
        public bool PrintRFId { get; set; }
        public bool PrintLabel { get; set; }
        public bool PrintList { get; set; }
        public string RFIdPrinter { get; set; }
        public Nullable<int> LabelPrinter { get; set; }
        public string Label { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> ListPrinter { get; set; }
        public string List { get; set; }
        public bool IsFollowProductionOrderSequence { get; set; }
        public Nullable<System.DateTime> ValidFromTime { get; set; }
        public bool Use48PartOrder { get; set; }
        public bool ScanLocation { get; set; }
        public Nullable<int> NoOfCycles { get; set; }
        public Nullable<int> ConnectedExecutionOrderTypeId { get; set; }
        public bool IsAutoPrintOutEnabled { get; set; }
        public bool IsExecutionOrderStart { get; set; }
        public bool KitInMultipleMasterGroup { get; set; }
        public string ColourCodeKit { get; set; }
        public string ColourCodeStartBtn { get; set; }
        public string ColourCodeEndBtn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual KitType KitType { get; set; }
        public virtual PartOrderType PartOrderType { get; set; }
        public virtual PhysicalAddressExtSystem PhysicalAddressExtSystem { get; set; }
        public virtual PickingGroup PickingGroup1 { get; set; }
        public virtual Printer Printer { get; set; }
        public virtual Printer Printer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPreAssemblyPickupLocation> KitPreAssemblyPickupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitTransportUnit> KitTransportUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterGroupEquipment> MasterGroupEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationDeliveryLocationKit> StationDeliveryLocationKits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationPartKit> StationPartKits { get; set; }
    }
}
