//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitPreAssemblyPickupLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitPreAssemblyPickupLocation()
        {
            this.KitPreAssemblyPickupLocationParts = new HashSet<KitPreAssemblyPickupLocationPart>();
        }
    
        public string KitId { get; set; }
        public string LocationId { get; set; }
        public bool MultiPickLocation { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Kit Kit { get; set; }
        public virtual KitPreAssemblyPickupLocation KitPreAssemblyPickupLocation1 { get; set; }
        public virtual KitPreAssemblyPickupLocation KitPreAssemblyPickupLocation2 { get; set; }
        public virtual KitPreAssemblyPickupLocation KitPreAssemblyPickupLocation11 { get; set; }
        public virtual KitPreAssemblyPickupLocation KitPreAssemblyPickupLocation3 { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPreAssemblyPickupLocationPart> KitPreAssemblyPickupLocationParts { get; set; }
    }
}
