//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitPickGroupStartSequence
    {
        public string KitPickgroupId { get; set; }
        public string Kitid { get; set; }
        public System.DateTime SentTime { get; set; }
        public string CreatedBy { get; set; }
        public int ObjectVersion { get; set; }
    }
}
