//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitPickDeliveryUnitPart
    {
        public string KitOrderNumber { get; set; }
        public string PartNumber { get; set; }
        public Nullable<decimal> QuantityToPick { get; set; }
        public Nullable<decimal> QuantityPicked { get; set; }
        public Nullable<System.DateTime> PickedDate { get; set; }
        public bool MultiPickLocation { get; set; }
        public Nullable<int> ObjectVersion { get; set; }
    
        public virtual KitPickDeliveryUnit KitPickDeliveryUnit { get; set; }
    }
}
