//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitPickDeliveryUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitPickDeliveryUnit()
        {
            this.KitPickDeliveryUnitKits = new HashSet<KitPickDeliveryUnitKit>();
            this.KitPickDeliveryUnitParts = new HashSet<KitPickDeliveryUnitPart>();
            this.KitPickLocations = new HashSet<KitPickLocation>();
            this.KitPickMasterGroups = new HashSet<KitPickMasterGroup>();
            this.MainPackages = new HashSet<MainPackage>();
        }
    
        public string KitOrderNumber { get; set; }
        public string KitId { get; set; }
        public string DeliveryUnit { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PlannedStartTime { get; set; }
        public bool Started { get; set; }
        public bool Picked { get; set; }
        public Nullable<System.DateTime> PickedDate { get; set; }
        public string KitPickGroupId { get; set; }
        public Nullable<int> KitPickGroupSequence { get; set; }
        public bool IsEmpty { get; set; }
        public Nullable<System.DateTime> SequenceTime { get; set; }
        public string PhysicalStation { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> StartedTime { get; set; }
        public string TriggerKitPickGroup { get; set; }
        public string StartedBy { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPickDeliveryUnitKit> KitPickDeliveryUnitKits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPickDeliveryUnitPart> KitPickDeliveryUnitParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPickLocation> KitPickLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPickMasterGroup> KitPickMasterGroups { get; set; }
        public virtual KitRepickOnRejectedDeliveryUnit KitRepickOnRejectedDeliveryUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackage> MainPackages { get; set; }
    }
}
