//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitRebreakResultPlanned
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KitRebreakResultPlanned()
        {
            this.KitRebreakErrorPlanneds = new HashSet<KitRebreakErrorPlanned>();
        }
    
        public string KitId { get; set; }
        public int FullRebreakRequestCount { get; set; }
        public int TriggeredOrderCount { get; set; }
        public int ProcessedOrderCount { get; set; }
        public int NumberOfErrors { get; set; }
        public string LastProcessedOrder { get; set; }
        public Nullable<System.DateTime> RequestedTime { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitRebreakErrorPlanned> KitRebreakErrorPlanneds { get; set; }
    }
}
