//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitRebreakErrorPlanned
    {
        public string KitId { get; set; }
        public string OrderNumber { get; set; }
        public string Error { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual KitRebreakResultPlanned KitRebreakResultPlanned { get; set; }
    }
}
