//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Label()
        {
            this.ComponentOrderHandlings = new HashSet<ComponentOrderHandling>();
            this.ComponentOrderHandlings1 = new HashSet<ComponentOrderHandling>();
            this.LabelFields = new HashSet<LabelField>();
            this.PrinterTypeLabels = new HashSet<PrinterTypeLabel>();
        }
    
        public string LabelName { get; set; }
        public string LabelTemplate { get; set; }
        public string LabelSystem { get; set; }
        public string LabelType { get; set; }
        public int ObjectVersion { get; set; }
        public string LabelDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentOrderHandling> ComponentOrderHandlings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentOrderHandling> ComponentOrderHandlings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelField> LabelFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrinterTypeLabel> PrinterTypeLabels { get; set; }
    }
}
