//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadListMainItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadListMainItem()
        {
            this.LoadListSubItems = new HashSet<LoadListSubItem>();
        }
    
        public int Id { get; set; }
        public string LoadListId { get; set; }
        public Nullable<int> LoadListSeqNo { get; set; }
        public Nullable<int> TrpOrderSeq { get; set; }
        public int TrpStatus { get; set; }
        public bool ScanStatus { get; set; }
        public int ComponentGroupId { get; set; }
        public string DispatchNoteNumber { get; set; }
        public bool ManualGrouping { get; set; }
        public int GroupingStatus { get; set; }
        public Nullable<int> PackagePosition { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual LoadList LoadList { get; set; }
        public virtual LoadListItemTrpStatu LoadListItemTrpStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadListSubItem> LoadListSubItems { get; set; }
    }
}
