//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadList()
        {
            this.LoadListDispatchNotes = new HashSet<LoadListDispatchNote>();
            this.LoadListMainItems = new HashSet<LoadListMainItem>();
        }
    
        public string LoadListId { get; set; }
        public string TrailerTypeId { get; set; }
        public string TrailerId { get; set; }
        public string DockArea { get; set; }
        public Nullable<int> LoadListStatusId { get; set; }
        public Nullable<bool> SequenceLoading { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<System.DateTime> ShipmentTime { get; set; }
        public bool Express { get; set; }
        public Nullable<int> MeansOfTransportIdExpress { get; set; }
        public Nullable<int> CustomsCode { get; set; }
        public string TransportDocumentNo { get; set; }
        public bool Proforma { get; set; }
        public string EEDNumber { get; set; }
        public bool IsEEDRegistered { get; set; }
        public string PreloadArea { get; set; }
        public string ContainerId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual LoadListStatu LoadListStatu { get; set; }
        public virtual SubPackageStatusCode SubPackageStatusCode { get; set; }
        public virtual Trailer Trailer { get; set; }
        public virtual TrailerType TrailerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadListDispatchNote> LoadListDispatchNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadListMainItem> LoadListMainItems { get; set; }
    }
}
