//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.ActivityLocations = new HashSet<ActivityLocation>();
            this.AlternateLocations = new HashSet<AlternateLocation>();
            this.AlternateLocations1 = new HashSet<AlternateLocation>();
            this.ComponentTransports = new HashSet<ComponentTransport>();
            this.ComponentTransports1 = new HashSet<ComponentTransport>();
            this.FirstOperationMachinings = new HashSet<FirstOperationMachining>();
            this.InventoryWithdrawalOnLocations = new HashSet<InventoryWithdrawalOnLocation>();
            this.KitPreAssemblyPickupLocations = new HashSet<KitPreAssemblyPickupLocation>();
            this.LastOperationMachinings = new HashSet<LastOperationMachining>();
            this.PartProcesses = new HashSet<PartProcess>();
            this.PartProcesses1 = new HashSet<PartProcess>();
            this.LocationBlockings = new HashSet<LocationBlocking>();
            this.LocationGroupLocations = new HashSet<LocationGroupLocation>();
            this.LocationPrinters = new HashSet<LocationPrinter>();
            this.LocationRejectCodes = new HashSet<LocationRejectCode>();
            this.MainPackages = new HashSet<MainPackage>();
            this.MainPackageLocations = new HashSet<MainPackageLocation>();
            this.MainPackageLocations1 = new HashSet<MainPackageLocation>();
            this.MasterGroupLocations = new HashSet<MasterGroupLocation>();
            this.PartOrders = new HashSet<PartOrder>();
            this.PickingGroups = new HashSet<PickingGroup>();
            this.PickingGroups1 = new HashSet<PickingGroup>();
            this.StationDeliveryLocations = new HashSet<StationDeliveryLocation>();
            this.TransportUnits = new HashSet<TransportUnit>();
            this.UserGoodsReceivingLocations = new HashSet<UserGoodsReceivingLocation>();
        }
    
        public string LocationId { get; set; }
        public string LocationDescription { get; set; }
        public string LocationType { get; set; }
        public string LocationStatus { get; set; }
        public int LocationCapacity { get; set; }
        public string OwningDepartment { get; set; }
        public int PalletFrames { get; set; }
        public int Crane { get; set; }
        public string Storage { get; set; }
        public int StorageSurface { get; set; }
        public int StorageLevel { get; set; }
        public Nullable<int> LocationDepth { get; set; }
        public int ZoneNumber { get; set; }
        public int AccessTime { get; set; }
        public string LocationCompanionId { get; set; }
        public Nullable<int> LocationPackageHandling { get; set; }
        public bool EmptyPallet { get; set; }
        public int MaximumTransportTo { get; set; }
        public string Gate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ImportedBy { get; set; }
        public Nullable<System.DateTime> ImportedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityLocation> ActivityLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateLocation> AlternateLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateLocation> AlternateLocations1 { get; set; }
        public virtual AlternateLocation AlternateLocation { get; set; }
        public virtual AvailableLocation AvailableLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentTransport> ComponentTransports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentTransport> ComponentTransports1 { get; set; }
        public virtual DeliveryLocation DeliveryLocation { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirstOperationMachining> FirstOperationMachinings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryWithdrawalOnLocation> InventoryWithdrawalOnLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPreAssemblyPickupLocation> KitPreAssemblyPickupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LastOperationMachining> LastOperationMachinings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcess> PartProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcess> PartProcesses1 { get; set; }
        public virtual LocationHandling LocationHandling { get; set; }
        public virtual LocationStatu LocationStatu { get; set; }
        public virtual LocationType LocationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationBlocking> LocationBlockings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationGroupLocation> LocationGroupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationPrinter> LocationPrinters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationRejectCode> LocationRejectCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackage> MainPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackageLocation> MainPackageLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackageLocation> MainPackageLocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterGroupLocation> MasterGroupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrder> PartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickingGroup> PickingGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickingGroup> PickingGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationDeliveryLocation> StationDeliveryLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportUnit> TransportUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGoodsReceivingLocation> UserGoodsReceivingLocations { get; set; }
    }
}
