//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockedExecutionOrder
    {
        public int Id { get; set; }
        public string DeliveryUnit { get; set; }
        public string ExecutionOrderId { get; set; }
        public string LockStatus { get; set; }
        public string LockCode { get; set; }
        public string LockText { get; set; }
        public string LockTextTranslation { get; set; }
        public string Comment { get; set; }
        public string EmployeeNo { get; set; }
        public System.DateTime EventTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
    }
}
