//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockReason
    {
        public long Id { get; set; }
        public long ReSequenceMessageId { get; set; }
        public string LockCode { get; set; }
        public string LockText { get; set; }
        public string LockTextTranslation { get; set; }
        public string Comment { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ResequenceMessage ResequenceMessage { get; set; }
    }
}
