//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoosePartItemBlocking
    {
        public int Id { get; set; }
        public int BlockedQuantity { get; set; }
        public System.DateTime BlockedToDate { get; set; }
        public string BlockedReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual LoosePartItem LoosePartItem { get; set; }
    }
}
