//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoosePartItemPick
    {
        public int Id { get; set; }
        public int LoosePartItemId { get; set; }
        public string PickingGroupId { get; set; }
        public string AssemblyOrder { get; set; }
        public string PartNumber { get; set; }
        public string BookedPackageSupplierId { get; set; }
        public string BookedPackageId { get; set; }
        public string BookedPackageLocation { get; set; }
        public int Quantity { get; set; }
        public string PartOrderNumber { get; set; }
        public int LocationSequence { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual LoosePartItem LoosePartItem { get; set; }
        public virtual PickingGroup PickingGroup { get; set; }
    }
}
