//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoosePartOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoosePartOrder()
        {
            this.LoosePartItems = new HashSet<LoosePartItem>();
        }
    
        public string CPOId { get; set; }
        public string MainOrderId { get; set; }
        public string MasterItemId { get; set; }
        public string ProductionOrderId { get; set; }
        public string ProductionOrderType { get; set; }
        public string SiteBusinessKey { get; set; }
        public string OrderState { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CustomerOrderSequence CustomerOrderSequence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoosePartItem> LoosePartItems { get; set; }
    }
}
