//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPackageLastStored
    {
        public string SupplierId { get; set; }
        public string MainPackageId { get; set; }
        public System.DateTime LastStoredTime { get; set; }
        public string LocationType { get; set; }
        public Nullable<System.DateTime> LastStoredTimeHistory { get; set; }
        public int ObjectVersion { get; set; }
    }
}
