//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPackagePicking
    {
        public int Id { get; set; }
        public string SupplierId { get; set; }
        public string MainPackageId { get; set; }
        public string PickingGroupId { get; set; }
        public string AssemblyOrder { get; set; }
        public string UserId { get; set; }
        public bool Active { get; set; }
        public Nullable<long> CustomerOrderheadId { get; set; }
        public Nullable<int> CustomsCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual CustomerOrderHead CustomerOrderHead { get; set; }
        public virtual PickingGroup PickingGroup { get; set; }
        public virtual SubPackageStatusCode SubPackageStatusCode { get; set; }
    }
}
