//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterGroup()
        {
            this.ComponentGroupExceptions = new HashSet<ComponentGroupException>();
            this.ComponentOrderHandlings = new HashSet<ComponentOrderHandling>();
            this.MainPackageDeliveryRoutes = new HashSet<MainPackageDeliveryRoute>();
            this.MasterGroupDescriptons = new HashSet<MasterGroupDescripton>();
            this.MasterGroupEquipments = new HashSet<MasterGroupEquipment>();
            this.MasterGroupLocations = new HashSet<MasterGroupLocation>();
            this.PartCharacteristics = new HashSet<PartCharacteristic>();
            this.PartOrders = new HashSet<PartOrder>();
            this.PickingGroupMasterGroups = new HashSet<PickingGroupMasterGroup>();
            this.TransportUnits = new HashSet<TransportUnit>();
        }
    
        public string MasterGroupId { get; set; }
        public string Description { get; set; }
        public bool TransportAssignmentButtonActivated { get; set; }
        public int MasterTypeId { get; set; }
        public Nullable<int> ConfirmationModeId { get; set; }
        public string SinglepackageLabelType { get; set; }
        public string MixedpackageLabelType { get; set; }
        public int TuggerCapacity { get; set; }
        public bool PickBoxByBox { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentGroupException> ComponentGroupExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentOrderHandling> ComponentOrderHandlings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPackageDeliveryRoute> MainPackageDeliveryRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterGroupDescripton> MasterGroupDescriptons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterGroupEquipment> MasterGroupEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterGroupLocation> MasterGroupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartCharacteristic> PartCharacteristics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrder> PartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickingGroupMasterGroup> PickingGroupMasterGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportUnit> TransportUnits { get; set; }
    }
}
