//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterGroupLocation
    {
        public string LocationId { get; set; }
        public string MasterGroupId { get; set; }
        public int PickingSequence { get; set; }
        public string PhysicalStartAddress { get; set; }
        public bool InventoryCount { get; set; }
        public Nullable<System.DateTime> LatestInventoryCount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MasterGroup MasterGroup { get; set; }
        public virtual PhysicalAddressExtSystem PhysicalAddressExtSystem { get; set; }
    }
}
