//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialHandlingCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialHandlingCode()
        {
            this.ExceptionsMaterialHandlingCodes = new HashSet<ExceptionsMaterialHandlingCode>();
            this.InventoryWithdrawalOnLocations = new HashSet<InventoryWithdrawalOnLocation>();
            this.MaterialHandlingCodeDescriptions = new HashSet<MaterialHandlingCodeDescription>();
            this.MaterialHandlingLotSizeExceptions = new HashSet<MaterialHandlingLotSizeException>();
        }
    
        public string MaterialHandlingCode1 { get; set; }
        public string Description { get; set; }
        public Nullable<int> PartOrderTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionsMaterialHandlingCode> ExceptionsMaterialHandlingCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryWithdrawalOnLocation> InventoryWithdrawalOnLocations { get; set; }
        public virtual PartOrderType PartOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHandlingCodeDescription> MaterialHandlingCodeDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHandlingLotSizeException> MaterialHandlingLotSizeExceptions { get; set; }
    }
}
