//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementWithoutTransport
    {
        public string PickUpLocation { get; set; }
        public string DeliveryLocation { get; set; }
        public bool AutoCompleteTRP { get; set; }
        public Nullable<int> ObjectVersion { get; set; }
    }
}
