//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackInstruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackInstruction()
        {
            this.PackInstructionSubPackages = new HashSet<PackInstructionSubPackage>();
        }
    
        public string SiteId { get; set; }
        public string SupplierId { get; set; }
        public string PartNumber { get; set; }
        public string InstructionId { get; set; }
        public string Status { get; set; }
        public string StatusDescription { get; set; }
        public bool PackagingInformation { get; set; }
        public string ReferenceNumber { get; set; }
        public string MainPackageType { get; set; }
        public Nullable<decimal> MainPackageQuantity { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public int ObjectVersion { get; set; }
        public string PackageType { get; set; }
    
        public virtual PalletTypeMapping PalletTypeMapping { get; set; }
        public virtual PartSupplier PartSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackInstructionSubPackage> PackInstructionSubPackages { get; set; }
    }
}
