//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PalletType()
        {
            this.InnerPackingWeights = new HashSet<InnerPackingWeight>();
            this.OrderHandlingExceptions = new HashSet<OrderHandlingException>();
            this.OrderHandlingExceptions1 = new HashSet<OrderHandlingException>();
            this.PackReferenceNumbers = new HashSet<PackReferenceNumber>();
            this.PalletTypeDepartmentLevels = new HashSet<PalletTypeDepartmentLevel>();
        }
    
        public int PalletTypeId { get; set; }
        public string PackageTypeId { get; set; }
        public int PalletFrames { get; set; }
        public string Description { get; set; }
        public int MaximumNumberOfPalletFrames { get; set; }
        public decimal PackageWeight { get; set; }
        public decimal PackageWeightDifference { get; set; }
        public decimal PackageMaximumWeight { get; set; }
        public int LoadLength { get; set; }
        public int LoadWidth { get; set; }
        public int LoadHeight { get; set; }
        public int NumberOfZeroWidthLocation { get; set; }
        public bool IsTrusted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerPackingWeight> InnerPackingWeights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHandlingException> OrderHandlingExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHandlingException> OrderHandlingExceptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackReferenceNumber> PackReferenceNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PalletTypeDepartmentLevel> PalletTypeDepartmentLevels { get; set; }
    }
}
