//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartProcess()
        {
            this.PartProcessUsePoints = new HashSet<PartProcessUsePoint>();
        }
    
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public string DeliveryLocationId { get; set; }
        public string Gate { get; set; }
        public string GoodsReceivingUnloadLocationId { get; set; }
        public string DeliveryPoint { get; set; }
        public int MaterialHandlingLotSize { get; set; }
        public string FDGConcatenated { get; set; }
        public System.DateTime ValidFromDate { get; set; }
        public string EmballageTypeId { get; set; }
        public int MRPInfoTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
        public string Receiver { get; set; }
        public bool OnlineBalance { get; set; }
    
        public virtual EmballageType EmballageType { get; set; }
        public virtual Gate Gate1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual MRPInfoType MRPInfoType { get; set; }
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcessUsePoint> PartProcessUsePoints { get; set; }
    }
}
