//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartCharacteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartCharacteristic()
        {
            this.PartCharacteristicExceptions = new HashSet<PartCharacteristicException>();
        }
    
        public string ReceivingDepartmentId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> OrderExecuteCategory { get; set; }
        public Nullable<int> OrderPointQuantity { get; set; }
        public Nullable<int> ReplenishmentQuantity { get; set; }
        public string ReceivingAdressLocation { get; set; }
        public string FixedReceivingDepartment { get; set; }
        public Nullable<int> PartStructureQuantity { get; set; }
        public Nullable<int> ZoneNumber { get; set; }
        public string LocationType { get; set; }
        public Nullable<int> LocationCapacity { get; set; }
        public bool FreePile { get; set; }
        public int MaxNumberOfPackage { get; set; }
        public string MasterGroupId { get; set; }
        public bool PushRepackGoodsReceiving { get; set; }
        public bool PushRepackNoReturn { get; set; }
        public string EmballageType { get; set; }
        public bool TransportViaId { get; set; }
        public Nullable<int> LotMaxRatio { get; set; }
        public Nullable<int> LotMinRatio { get; set; }
        public int ReplenishmentMode { get; set; }
        public Nullable<int> PickOrderType { get; set; }
        public bool IdSplit { get; set; }
        public bool IdSplitLogicalPack { get; set; }
        public bool PreparedForCustomer { get; set; }
        public bool ReturnFromExternalPicking { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ImportedBy { get; set; }
        public Nullable<System.DateTime> ImportedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual LocationType LocationType1 { get; set; }
        public virtual MasterGroup MasterGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartCharacteristicException> PartCharacteristicExceptions { get; set; }
    }
}
