//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartCharacteristicException
    {
        public string ReceivingDepartmentId { get; set; }
        public string PartNumber { get; set; }
        public int StatusOfPackage { get; set; }
        public Nullable<int> OrderPointQuantity { get; set; }
        public Nullable<int> ReplenishmentQuantity { get; set; }
        public Nullable<int> ZoneNumber { get; set; }
        public string ReceivingAdressLocation { get; set; }
        public Nullable<int> MaterialHandlingQuantity { get; set; }
        public string PackReferenceNumber { get; set; }
        public int PercentageOfBusiness { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ImportedBy { get; set; }
        public Nullable<System.DateTime> ImportedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual PartCharacteristic PartCharacteristic { get; set; }
    }
}
