//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartProcessUsePoint
    {
        public int Id { get; set; }
        public int PartProcessID { get; set; }
        public Nullable<int> StationPartId { get; set; }
        public int Objectversion { get; set; }
    
        public virtual PartProcess PartProcess { get; set; }
        public virtual StationPart StationPart { get; set; }
    }
}
