//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.AutoreplyOnParts = new HashSet<AutoreplyOnPart>();
            this.AutoreplyOnPartAndDeliveryPoints = new HashSet<AutoreplyOnPartAndDeliveryPoint>();
            this.CustomerReceiverParts = new HashSet<CustomerReceiverPart>();
            this.DispatchInvoiceInfoBasics = new HashSet<DispatchInvoiceInfoBasic>();
            this.ExternalParts = new HashSet<ExternalPart>();
            this.FirstOperationMachinings = new HashSet<FirstOperationMachining>();
            this.LastOperationMachinings = new HashSet<LastOperationMachining>();
            this.MaterialHandlingLotSizes = new HashSet<MaterialHandlingLotSize>();
            this.PartAttributes = new HashSet<PartAttribute>();
            this.PartDescriptions = new HashSet<PartDescription>();
            this.PartExceptions = new HashSet<PartException>();
            this.PartOrders = new HashSet<PartOrder>();
            this.PartProcesses = new HashSet<PartProcess>();
            this.PartSuppliers = new HashSet<PartSupplier>();
            this.PickingInstructions = new HashSet<PickingInstruction>();
            this.SubPackages = new HashSet<SubPackage>();
        }
    
        public string PartNumber { get; set; }
        public string PartStatus { get; set; }
        public string PartCode { get; set; }
        public string DescriptionSupplementary { get; set; }
        public string MaterialHandlingCode { get; set; }
        public string MaterialControllerId { get; set; }
        public Nullable<decimal> WeightPerPart { get; set; }
        public string ChangeNoteStartNotice { get; set; }
        public string ChangeNoteEndNotice { get; set; }
        public Nullable<System.DateTime> ChangeNoteDateFrom { get; set; }
        public Nullable<System.DateTime> ChangeNoteDateTo { get; set; }
        public Nullable<System.DateTime> PartProductionDateFrom { get; set; }
        public Nullable<System.DateTime> PartProductionDateTo { get; set; }
        public int LeadTime { get; set; }
        public string FieldNo { get; set; }
        public bool ProductCostCaculationPart { get; set; }
        public string PartVolumeValueClassification { get; set; }
        public Nullable<decimal> PartAnnualVolumeValue { get; set; }
        public Nullable<decimal> PartAnnualVolumeQuantity { get; set; }
        public string StandardCost { get; set; }
        public string SiteId { get; set; }
        public string CurrencyCode { get; set; }
        public string DepartmentId { get; set; }
        public string UnloadListNotification { get; set; }
        public string SatelliteStorageId { get; set; }
        public string InspectionLocation { get; set; }
        public bool PickingPart { get; set; }
        public bool PartMixAllowed { get; set; }
        public bool SubContracting { get; set; }
        public bool Repack { get; set; }
        public string Unit { get; set; }
        public bool SkipIdManualGR { get; set; }
        public string UoMToUoPConvertFactor { get; set; }
        public Nullable<System.DateTime> ModifiedTimePartSystem { get; set; }
        public bool IsWeightChangedManually { get; set; }
        public string PartPackabilityCode { get; set; }
        public string PartNoClassification { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoreplyOnPart> AutoreplyOnParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoreplyOnPartAndDeliveryPoint> AutoreplyOnPartAndDeliveryPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReceiverPart> CustomerReceiverParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchInvoiceInfoBasic> DispatchInvoiceInfoBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalPart> ExternalParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirstOperationMachining> FirstOperationMachinings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LastOperationMachining> LastOperationMachinings { get; set; }
        public virtual MaterialController MaterialController { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHandlingLotSize> MaterialHandlingLotSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartAttribute> PartAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartDescription> PartDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartException> PartExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrder> PartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcess> PartProcesses { get; set; }
        public virtual PartRestriction PartRestriction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartSupplier> PartSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickingInstruction> PickingInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubPackage> SubPackages { get; set; }
    }
}
