//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartException
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartException()
        {
            this.PartGroupKittings = new HashSet<PartGroupKitting>();
        }
    
        public string LocationId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> PartOrderTypeId { get; set; }
        public int QuantityOfMaterialToHandle { get; set; }
        public bool Ordered { get; set; }
        public string EmballageTypeId { get; set; }
        public int ProposedNoOfOrders { get; set; }
        public bool ActivateProposedNoOfOrders { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string ImportedBy { get; set; }
        public Nullable<System.DateTime> ImportedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual DeliveryLocation DeliveryLocation { get; set; }
        public virtual Part Part { get; set; }
        public virtual PartOrderType PartOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartGroupKitting> PartGroupKittings { get; set; }
    }
}
