//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartOrderType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartOrderType()
        {
            this.ExceptionsMaterialHandlingCodes = new HashSet<ExceptionsMaterialHandlingCode>();
            this.Kits = new HashSet<Kit>();
            this.MaterialHandlingCodes = new HashSet<MaterialHandlingCode>();
            this.MaterialHandlingLotSizeExceptions = new HashSet<MaterialHandlingLotSizeException>();
            this.PartExceptions = new HashSet<PartException>();
            this.PartOrders = new HashSet<PartOrder>();
            this.PartOrderTypeChangesAlloweds = new HashSet<PartOrderTypeChangesAllowed>();
            this.PartOrderTypeChangesAlloweds1 = new HashSet<PartOrderTypeChangesAllowed>();
            this.PartOrderTypeDescriptions = new HashSet<PartOrderTypeDescription>();
            this.ReplenishmentTemplates = new HashSet<ReplenishmentTemplate>();
        }
    
        public int PartOrderTypeId { get; set; }
        public string Description { get; set; }
        public bool DeleteAllowed { get; set; }
        public bool DeleteWhenTransportCancelled { get; set; }
        public bool Pick { get; set; }
        public bool MultiNeedTimeChangeAllowed { get; set; }
        public Nullable<int> MasterTypeId { get; set; }
        public bool ToPick { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionsMaterialHandlingCode> ExceptionsMaterialHandlingCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kit> Kits { get; set; }
        public virtual MasterType MasterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHandlingCode> MaterialHandlingCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHandlingLotSizeException> MaterialHandlingLotSizeExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartException> PartExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrder> PartOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderTypeChangesAllowed> PartOrderTypeChangesAlloweds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderTypeChangesAllowed> PartOrderTypeChangesAlloweds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderTypeDescription> PartOrderTypeDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplenishmentTemplate> ReplenishmentTemplates { get; set; }
    }
}
