//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickingInstruction
    {
        public int PickingInstructionId { get; set; }
        public string PictureName { get; set; }
        public string PartNumber { get; set; }
        public string Customer { get; set; }
        public string Receiver { get; set; }
        public byte[] Picture { get; set; }
        public int Sequence { get; set; }
        public bool ShowInstruction { get; set; }
        public Nullable<int> QtyLabelsToPrint { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
