//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreliminaryLoading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreliminaryLoading()
        {
            this.DeliveryNotes = new HashSet<DeliveryNote>();
        }
    
        public int PreliminaryCarrierId { get; set; }
        public System.DateTime GateTime { get; set; }
        public bool LoadingCoOrdination { get; set; }
        public int FreeLoadWeight { get; set; }
        public int FreeLoadSize { get; set; }
        public string Customer { get; set; }
        public int ReceptionId { get; set; }
        public int CarrierType { get; set; }
        public int LoadStatus { get; set; }
        public bool Express { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryNote> DeliveryNotes { get; set; }
    }
}
