//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public string SiteId { get; set; }
        public string SupplierId { get; set; }
        public string GPSOrderNumber { get; set; }
        public string PartNumber { get; set; }
        public decimal OrderPrice { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public string UnitCode { get; set; }
        public string CountryOfOrigin { get; set; }
        public string SupplierPartNumber { get; set; }
        public string PartRevision { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    }
}
