//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionPartNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceptionPartNumber()
        {
            this.ExternalCustomerReceiverParts = new HashSet<ExternalCustomerReceiverPart>();
        }
    
        public string ReceptionId { get; set; }
        public string PartNumber { get; set; }
        public int PriceValidFromDate { get; set; }
        public int ProductsPriceInBaseCurrency { get; set; }
        public int PriceOfFreight { get; set; }
        public int ProductsPriceInReceiversCurrency { get; set; }
        public int PriceOfFreightInReceiversCurrency { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCustomerReceiverPart> ExternalCustomerReceiverParts { get; set; }
    }
}
