//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingException
    {
        public int Id { get; set; }
        public System.DateTime EventTime { get; set; }
        public int RejectCode { get; set; }
        public string SupplierId { get; set; }
        public string MainPackageId { get; set; }
        public string SubPackageId { get; set; }
        public string PartNumber { get; set; }
        public string MaterialHandlingUnit { get; set; }
        public string ShipmentNoticeId { get; set; }
        public Nullable<System.DateTime> ResolveTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual RejectCode RejectCode1 { get; set; }
    }
}
