//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResequenceMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResequenceMessage()
        {
            this.LockReasons = new HashSet<LockReason>();
        }
    
        public long Id { get; set; }
        public string EventType { get; set; }
        public string MainOrder { get; set; }
        public string DeliveryUnit { get; set; }
        public string ExecutionOrder { get; set; }
        public Nullable<System.DateTime> EarliestStartTime { get; set; }
        public string SegmentState { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public bool IsProcessed { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LockReason> LockReasons { get; set; }
    }
}
