//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceNumber
    {
        public int ProfitCenterId { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public int MinNumber { get; set; }
        public int MaxNumber { get; set; }
        public int NextItemInInterval { get; set; }
        public string LastUsedGroupID { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ProfitCenter ProfitCenter { get; set; }
    }
}
