//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.ShipmentDispatchNotes = new HashSet<ShipmentDispatchNote>();
        }
    
        public int Id { get; set; }
        public string ShippingListNo { get; set; }
        public Nullable<System.DateTime> ShippingTime { get; set; }
        public string Carrier { get; set; }
        public string CarrierName { get; set; }
        public string CarrierStreet { get; set; }
        public string CarrierZipCode { get; set; }
        public string CarrierPostalAddress { get; set; }
        public string CarrierCity { get; set; }
        public string CarrierCountry { get; set; }
        public string CarrierContact { get; set; }
        public string CarrierContactPhone { get; set; }
        public string CarrierContactFax { get; set; }
        public string CarrierContactEmail { get; set; }
        public string TrailerNumber { get; set; }
        public string Sender { get; set; }
        public string SenderName { get; set; }
        public string SenderStreet { get; set; }
        public string SenderZipCode { get; set; }
        public string SenderPostalAddress { get; set; }
        public string SenderCity { get; set; }
        public string SenderCountry { get; set; }
        public string SenderContact { get; set; }
        public string SenderContactPhone { get; set; }
        public string SenderContactFax { get; set; }
        public string SenderContactEmail { get; set; }
        public string SealNumber { get; set; }
        public bool Prepaid { get; set; }
        public bool Collect { get; set; }
        public string EEDNumber { get; set; }
        public string ContainerId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDispatchNote> ShipmentDispatchNotes { get; set; }
    }
}
