//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDispatchNotePackagePartIncludedPart
    {
        public int Id { get; set; }
        public Nullable<int> ShipmentDispatchNotePackagePartId { get; set; }
        public Nullable<System.DateTime> ProductionTime { get; set; }
        public string PartNumber { get; set; }
        public string SerialNumber { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ShipmentDispatchNotePackagePart ShipmentDispatchNotePackagePart { get; set; }
    }
}
