//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDispatchNotePackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipmentDispatchNotePackage()
        {
            this.ShipmentDispatchNotePackageParts = new HashSet<ShipmentDispatchNotePackagePart>();
        }
    
        public int Id { get; set; }
        public int ShipmentDispatchNoteId { get; set; }
        public string PackageId { get; set; }
        public string PackageType { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string PackageReferenceNumber { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string LinesetNumber { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ShipmentDispatchNote ShipmentDispatchNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDispatchNotePackagePart> ShipmentDispatchNotePackageParts { get; set; }
    }
}
