//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDispatchNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipmentDispatchNote()
        {
            this.ShipmentDispatchNotePackages = new HashSet<ShipmentDispatchNotePackage>();
        }
    
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public string DispatchNoteNo { get; set; }
        public string Customer { get; set; }
        public string Receiver { get; set; }
        public string Flow { get; set; }
        public string EndFactory { get; set; }
        public string Gate { get; set; }
        public Nullable<int> NumberOfPackages { get; set; }
        public Nullable<bool> ASN { get; set; }
        public Nullable<bool> Customs { get; set; }
        public Nullable<bool> InternalCustomer { get; set; }
        public int ObjectVersion { get; set; }
        public string ConsignmentNoteID { get; set; }
        public string KDBatchNo_ { get; set; }
    
        public virtual Shipment Shipment { get; set; }
        public virtual ShipmentDispatchNoteDetail ShipmentDispatchNoteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDispatchNotePackage> ShipmentDispatchNotePackages { get; set; }
    }
}
