//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDispatchNotePackagePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipmentDispatchNotePackagePart()
        {
            this.ShipmentDispatchNotePackagePartIncludedParts = new HashSet<ShipmentDispatchNotePackagePartIncludedPart>();
            this.ShipmentDispatchNotePackagePartProdOrders = new HashSet<ShipmentDispatchNotePackagePartProdOrder>();
        }
    
        public int Id { get; set; }
        public int ShipmentDispatchNotePackageId { get; set; }
        public string SubPackageId { get; set; }
        public string PackageReferenceNumber { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public string PCId { get; set; }
        public string CPOId { get; set; }
        public string DeliveryUnit { get; set; }
        public string InternalOrderNumber { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string SalesOrderNumber { get; set; }
        public string InvoiceOrderNumber { get; set; }
        public string PurchaseId { get; set; }
        public string ComNumber { get; set; }
        public string VSMCNumber { get; set; }
        public string ComponentType { get; set; }
        public string CompFamily { get; set; }
        public string ChassieType { get; set; }
        public Nullable<int> ChassieNumber { get; set; }
        public string EnginePrefix { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string Batch { get; set; }
        public Nullable<int> ShipmentDeliveryNumber { get; set; }
        public string CustomerPartNumber { get; set; }
        public string PentaPartNumber { get; set; }
        public string CustomerReferenceNumber { get; set; }
        public string CountryOfOrigin { get; set; }
        public string DeliveryId { get; set; }
        public string PartDescription { get; set; }
        public string ASNPartNumber { get; set; }
        public string CustomsCode { get; set; }
        public Nullable<System.DateTime> ProductionTime { get; set; }
        public string HSClassification { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string PricingUnit { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InternalOrderId { get; set; }
        public string UsePoint { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual ShipmentDispatchNotePackage ShipmentDispatchNotePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDispatchNotePackagePartIncludedPart> ShipmentDispatchNotePackagePartIncludedParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDispatchNotePackagePartProdOrder> ShipmentDispatchNotePackagePartProdOrders { get; set; }
    }
}
