//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationPart()
        {
            this.KitPreAssemblyPickupLocationParts = new HashSet<KitPreAssemblyPickupLocationPart>();
            this.PartProcessUsePoints = new HashSet<PartProcessUsePoint>();
            this.StationPartKits = new HashSet<StationPartKit>();
        }
    
        public int StationPartId { get; set; }
        public string PartNumber { get; set; }
        public int StationChangeNoteId { get; set; }
        public Nullable<int> PartOrderTypeId { get; set; }
        public Nullable<int> TriggerTypeId { get; set; }
        public string TriggerPoint { get; set; }
        public Nullable<int> InventoryWithdrawalTypeId { get; set; }
        public string InventoryWithdrawalPoint { get; set; }
        public Nullable<int> OrderPointQuantity { get; set; }
        public Nullable<int> ReplenishQuantity { get; set; }
        public string EmballageTypeId { get; set; }
        public bool FromStructure { get; set; }
        public int Quantity { get; set; }
        public System.DateTime FirstTimeUsed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitPreAssemblyPickupLocationPart> KitPreAssemblyPickupLocationParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartProcessUsePoint> PartProcessUsePoints { get; set; }
        public virtual StationChangeNote StationChangeNote { get; set; }
        public virtual StationDeliveryLocationPart StationDeliveryLocationPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationPartKit> StationPartKits { get; set; }
    }
}
