//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationDeliveryLocationPart
    {
        public int StationPartId { get; set; }
        public int StationDeliveryLocationId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
        public bool OnlineBalance { get; set; }
    
        public virtual StationDeliveryLocation StationDeliveryLocation { get; set; }
        public virtual StationPart StationPart { get; set; }
    }
}
