//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakingAdjustment
    {
        public int Id { get; set; }
        public int StateId { get; set; }
        public string LocationId { get; set; }
        public string PartNumber { get; set; }
        public int Adjustment { get; set; }
        public bool ProcessLocation { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual StockTakingState StockTakingState { get; set; }
    }
}
