//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPackageBooking
    {
        public long Id { get; set; }
        public string PackageSupplierId { get; set; }
        public string PackageId { get; set; }
        public string PartOrderNumber { get; set; }
        public string PartNumber { get; set; }
        public int NumberOfBookedItemsInPackage { get; set; }
        public System.DateTime BookedTimeForPackage { get; set; }
        public string PackageBookingLocation { get; set; }
        public string UserId { get; set; }
        public System.DateTime AdmissibleStartTime { get; set; }
        public int TransportAssignmentPriority { get; set; }
        public Nullable<int> SubPackageBookingCodeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual PartOrder PartOrder { get; set; }
        public virtual SubPackageBookingCode SubPackageBookingCode { get; set; }
    }
}
