//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Addresses = new HashSet<Address>();
            this.PartSuppliers = new HashSet<PartSupplier>();
        }
    
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string SiteId { get; set; }
        public string LaguageCode { get; set; }
        public string Country { get; set; }
        public string PurchaseOrderType { get; set; }
        public int EdiDeliveryScheduleStatus { get; set; }
        public string Carrier { get; set; }
        public Nullable<int> EdiStatusId { get; set; }
        public string ReceiveNotification { get; set; }
        public bool ReceiptNoteRequired { get; set; }
        public string EMail { get; set; }
        public bool VMISupplier { get; set; }
        public int DefaultRetentionTimeVMI { get; set; }
        public string SatelliteStorageId { get; set; }
        public bool SkipIdManualGR { get; set; }
        public bool AutomaticGoodsReceive { get; set; }
        public string VMLCSupplier { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
        public bool DoNotUseExternalPackageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual EdiStatu EdiStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartSupplier> PartSuppliers { get; set; }
    }
}
