//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemParameter()
        {
            this.DepartmentSystemParameters = new HashSet<DepartmentSystemParameter>();
            this.FactorySystemParameters = new HashSet<FactorySystemParameter>();
            this.FunctionSystemParameterMappings = new HashSet<FunctionSystemParameterMapping>();
            this.ProfitCenterSystemParameters = new HashSet<ProfitCenterSystemParameter>();
            this.SystemParameterValues = new HashSet<SystemParameterValue>();
        }
    
        public string ParameterId { get; set; }
        public string ParameterTypeDesc { get; set; }
        public Nullable<int> ParameterCategoryId { get; set; }
        public string Value { get; set; }
        public bool SuperUser { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentSystemParameter> DepartmentSystemParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactorySystemParameter> FactorySystemParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionSystemParameterMapping> FunctionSystemParameterMappings { get; set; }
        public virtual ParameterCategory ParameterCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfitCenterSystemParameter> ProfitCenterSystemParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemParameterValue> SystemParameterValues { get; set; }
    }
}
