//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportUnit()
        {
            this.KitTransportUnits = new HashSet<KitTransportUnit>();
            this.TransportUnitLoads = new HashSet<TransportUnitLoad>();
        }
    
        public string TransportUnitId { get; set; }
        public string TransportUnitDescription { get; set; }
        public string TransportTypeId { get; set; }
        public int Level { get; set; }
        public int Stow { get; set; }
        public string MasterGroupId { get; set; }
        public string LocationId { get; set; }
        public bool IsFull { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitTransportUnit> KitTransportUnits { get; set; }
        public virtual Location Location { get; set; }
        public virtual MasterGroup MasterGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportUnitLoad> TransportUnitLoads { get; set; }
    }
}
