//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnloadListDetail
    {
        public int UnloadId { get; set; }
        public string SupplierId { get; set; }
        public string ShipmentNoticeId { get; set; }
        public string PartNumber { get; set; }
        public string MaterialHandlingUnit { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> InspectionQuantity { get; set; }
        public Nullable<bool> Express { get; set; }
        public string OtherDestination { get; set; }
        public string Status { get; set; }
        public string FixedDepartment { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public int ObjectVersion { get; set; }
    
        public virtual UnloadList UnloadList { get; set; }
    }
}
