//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDA.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UoMToUoPConvert
    {
        public string FromTo { get; set; }
        public string ArithmeticOperator { get; set; }
        public int ConvertFactor { get; set; }
        public string Description { get; set; }
        public string UoM { get; set; }
        public string UoP { get; set; }
        public int ObjectVersion { get; set; }
    }
}
